- name: BeegGFS Common Configuration
  hosts: allmachines
  become: true
  become_user: root
  tasks:
  - name: install new kernel
    shell: "sudo dnf install kernel-devel-5.14.0-284.11.1.el9_2.x86_64 -y"
  - name: Create mount location
    ansible.builtin.file:
      path: /beegfs
      state: directory
  - name: Configure client
    ansible.builtin.command:
      cmd: /opt/beegfs/sbin/beegfs-setup-client -m ip-10-0-10-29
  - name: Auth file
    ansible.builtin.copy:
      src: connauthfile
      dest: /etc/beegfs/connauthfile
      owner: root
      group: root
      mode: 400
  - name: Mounts file
    ansible.builtin.copy:
      src: beegfs-mounts.conf
      dest: /etc/beegfs/beegfs-mounts.conf
      owner: root
      group: root
  - name: fix helperconf
    ansible.builtin.replace:
      path: /etc/beegfs/beegfs-helperd.conf
      regexp: 'connAuthFile       ='
      replace: 'connAuthFile=/etc/beegfs/connauthfile'
  - name: fix helperconf 2
    ansible.builtin.replace:
      path: /etc/beegfs/beegfs-helperd.conf
      regexp: 'connAuthFile                  ='
      replace: 'connAuthFile=/etc/beegfs/connauthfile'
  - name: fix client conf
    ansible.builtin.replace:
      path: /etc/beegfs/beegfs-client.conf
      regexp: 'connAuthFile                  ='
      replace: 'connAuthFile=/etc/beegfs/connauthfile'
  - name: start helperd
    ansible.builtin.systemd_service:
      name: beegfs-helperd
      state: started
      enabled: true
  - name: start client
    ansible.builtin.systemd_service:
      name: beegfs-client
      state: started
      enabled: true

