- name: Run consumer
  hosts: clusterworker
  tasks:
    - name: Run consumer
      ansible.builtin.shell: |
        chmod +x /beegfs/pipeline/runConsumer.sh
        nohup /beegfs/pipeline/runConsumer.sh &
