- name: Prometheus setup
  hosts: localhost
  tasks:
    - name: Prometheus setup
      ansible.builtin.shell: |
        mkdir /beegfs/prometheus
        cd /beegfs/pipeline
        tar xvfz prometheus-2.45.4.linux-amd64.tar.gz --directory /beegfs/prometheus/
        tar xvfz node_exporter-1.7.0.linux-amd64.tar.gz  --directory /beegfs/prometheus/
        cd /beegfs/prometheus
        mv prometheus-2.45.4.linux-amd64 prometheus-2.45.4
        mv node_exporter-1.7.0.linux-amd64 node_exporter-1.7.0